source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'ActorKitTests' do
  pod 'ActorKit', :path => '../'
  pod 'ActorKit/Supervision', :path => '../'
  pod 'ActorKit/Promises', :path => '../'

  pod 'Specta'
  pod 'Expecta'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |configuration|
            configuration.build_settings['SWIFT_VERSION'] = "3.0"
        end
    end
end