source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'ActorKitTests' do
  pod 'ActorKit', :path => '../'
  pod 'ActorKit/Supervision', :path => '../'
  pod 'ActorKit/Promises', :path => '../'

  pod 'Specta'
  pod 'Expecta'
end
