source 'https://github.com/CocoaPods/Specs.git'

target 'ActorKitTests', :exclusive => true do
  pod "ActorKit", :path => "../"
  pod "ActorKit/Futures", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
